template_builder:
  project_title: "Template Builder"
  filled_up_by: "Muttalib Hossain"
  github_link: "https://github.com/a2i-dpg/template-builder.git"
  ticket_contents: |
    A template builder is a tool for creating standardized document layouts quickly. It offers a user-friendly interface to design templates, ensuring consistency in formatting for various purposes such as certificates or official letters. Users can choose pre-designed templates or customize their own, streamlining the document creation process.

    Ticket Description:
    1. Need to create a template registry from where a drag and drop template can be added in the template builder.
    2. Ui/Ux design can be enhanced.
    3. Make the system integratable or convert as a package so that it can be considered as plug and play with other systems.
    4. Digital signature needs to be integrated for the approver and the applicant.
  goals_and_milestones: |
    Goals for a Template Builder:
    - User-Friendly Interface: Develop an intuitive and user-friendly design for easy template creation.
    - Versatility: Provide a tool that caters to various document types and purposes.
    - Consistency: Ensure templates maintain a consistent look and feel across different sections.
    - Customization: Enable users to easily customize templates to meet their specific needs.
    - Efficiency: Streamline the document creation process, saving users time and effort.
    - Compatibility: Ensure compatibility with popular document formats and software.
    - Collaboration: Allow users to collaborate on template creation, facilitating team workflows.

    Milestones for a Template Builder:
    - Prototype Development: Create an initial version showcasing basic template-building functionalities.
    - User Testing: Gather feedback from users to refine and improve the template builder's usability.
    - Template Library Establishment: Build a library of pre-designed templates for user convenience.
    - Customization Features: Implement advanced customization options for diverse user needs.
    - Compatibility Testing: Ensure seamless integration with various document formats and software.
    - Collaboration Tools Integration: Integrate features that allow users to collaborate on template creation.
    - Official Release: Launch the template builder to the public, marking its availability for general use.
  setup_installation_guide_link: "https://template-workflow.live.mygov.bd"
  expected_outcome: "Make the product as Plug and Playable, more integratable, and user friendly."
  acceptance_criteria: "N/A"
  implementation_details: |
    - Installations guidelines:
      1. Clone your project
      2. Go to the folder application using cd command on your cmd or terminal
      3. Run composer install on your cmd or terminal
      4. Copy .env.example file to .env on the root folder. You can type copy .env.example .env if using command prompt Windows or cp .env.example .env if using terminal, Ubuntu
      5. Open your .env file and change the database name (DB_DATABASE) to whatever you have, username (DB_USERNAME) and password (DB_PASSWORD) field correspond to your configuration.
      6. Run php artisan key:generate
      7. Run php artisan migrate
      8. Run php artisan serve
      9. Go to http://localhost:8000/
  mockup_wireframes_links: "N/A"
  domain_link: "https://template-workflow.live.mygov.bd"
  required_tech_skills: "basic PHP and Laravel framework"
  mentors_focals: "N/A"
  product_category: "Template Builder"
